inputs = ["index.dlt","./chapters/chapter_0/ch_0_aprender.dlt","./chapters/chapter_1/chapter_1.dlt", "./chapters/chapter_2/chapter_2.dlt", "./chapters/chapter_3/chapter_3.dlt"]
out = "docs"
packages = ["regression"]

[document]
theme="theme.css"
theme-accent="red"
theme-mode="light"
lang="pt"
